FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    zip \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY requirements.txt .

RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

COPY . /workspace/lambda/

ENTRYPOINT ["/bin/bash", "-c", "/workspace/lambda/setup_lambdas.sh"]